version: '3.8'
services:
    api-service:
        build: ./api/
        volumes:
            - ./api/:/usr/src/app/
        ports:
            - 4000:4000
        environment:
            PORT: 4000
            FLASK_DEBUG: 1
