version: '3.8'
services:
  api:
    build: ./api/
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      FLASK_DEBUG: 1
      DATABASE_URL: mysql://api:api@db/api
    depends_on:
      - db
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "api"
      MYSQL_USER: "api"
      MYSQL_PASSWORD: "api"
